### ISSUE TITLE
ilastik 1.2.0 does not start due to python import problem with decodelzw

### ISSUE THREAD

**Issue by sebi06** [ilastik/ilastik#1415]
Hi guys,

when I start my freshly installed ilastik 1.20 on Windows 7 64bit it does not work gives the following error messages:

Starting ilastik from "C:\Program Files\ilastik".
ERROR 2017-02-09 10:07:37,319 excepthooks 10796 8920 Unhandled exception in thre
ad: 'MainThread'
ERROR 2017-02-09 10:07:37,323 excepthooks 10796 8920 Traceback (most recent call
 last):
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\shell\gui\startShe
llGui.py", line 91, in launchShell
    from ilastik.shell.gui.ilastikShell import IlastikShell
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\shell\gui\ilastikS
hell.py", line 83, in <module>
    import ilastik.workflows
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\workflows\__init__
.py", line 28, in <module>
    import pixelClassification
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\workflows\pixelCla
ssification\__init__.py", line 21, in <module>
    from pixelClassificationWorkflow import PixelClassificationWorkflow
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\workflows\pixelCla
ssification\pixelClassificationWorkflow.py", line 33, in <module>
    from ilastik.applets.dataSelection import DataSelectionApplet
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\dataSelect
ion\__init__.py", line 21, in <module>
    from dataSelectionApplet import OpMultiLaneDataSelectionGroup, DataSelection
Applet
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\dataSelect
ion\dataSelectionApplet.py", line 32, in <module>
    from opDataSelection import OpMultiLaneDataSelectionGroup, DatasetInfo
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\dataSelect
ion\opDataSelection.py", line 29, in <module>
    from lazyflow.operators.ioOperators import OpStreamingHdf5Reader, OpInputDat
aReader
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\ioOper
ators\__init__.py", line 48, in <module>
    from opInputDataReader import *
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\ioOper
ators\opInputDataReader.py", line 27, in <module>
    from opTiffReader import OpTiffReader
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\ioOper
ators\opTiffReader.py", line 10, in <module>
    if tifffile.decodelzw != _tifffile.decodelzw:
AttributeError: 'module' object has no attribute 'decodelzw'

**Comment by stuarteberg** [comment]
Thanks for the report.  It looks like there may be a problem with our tiff-reading package, at least on Windows.

@ukoethe, did the `tifffile` C-extension get built correctly for the 1.2.0 binary?

**Comment by sebi06** [comment]
It is still not working with 1.2.2rc3

Starting ilastik from "C:\Program Files\ilastik".
ERROR 2017-05-22 10:58:53,431 excepthooks 7912 15040 Unhandled exception in thre
ad: 'MainThread'
ERROR 2017-05-22 10:58:53,434 excepthooks 7912 15040 Traceback (most recent call
 last):
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\shell\gui\startShe
llGui.py", line 91, in launchShell
    from ilastik.shell.gui.ilastikShell import IlastikShell
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\shell\gui\ilastikS
hell.py", line 83, in <module>
    import ilastik.workflows
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\workflows\__init__
.py", line 28, in <module>
    import pixelClassification
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\workflows\pixelCla
ssification\__init__.py", line 21, in <module>
    from pixelClassificationWorkflow import PixelClassificationWorkflow
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\workflows\pixelCla
ssification\pixelClassificationWorkflow.py", line 32, in <module>
    from ilastik.applets.dataSelection import DataSelectionApplet
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\dataSelect
ion\__init__.py", line 21, in <module>
    from dataSelectionApplet import OpMultiLaneDataSelectionGroup, DataSelection
Applet
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\dataSelect
ion\dataSelectionApplet.py", line 32, in <module>
    from opDataSelection import OpMultiLaneDataSelectionGroup, DatasetInfo
  File "C:\Program Files\ilastik\ilastik-meta\ilastik\ilastik\applets\dataSelect
ion\opDataSelection.py", line 29, in <module>
    from lazyflow.operators.ioOperators import OpStreamingHdf5Reader, OpInputDat
aReader
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\ioOper
ators\__init__.py", line 38, in <module>
    from opTiffReader import OpTiffReader
  File "C:\Program Files\ilastik\ilastik-meta\lazyflow\lazyflow\operators\ioOper
ators\opTiffReader.py", line 10, in <module>
    if tifffile.decodelzw != _tifffile.decodelzw:
AttributeError: 'module' object has no attribute 'decodelzw'

**Comment by akreshuk** [comment]
@k-dominik , since you were on the problem of input tests just recently, could you add another one for compressed tiff? This should make the debugging of this one easier.

**Comment by sebi06** [comment]
Maybe  stupid remark, but may this be a typo? decodelzw vs decode_lzw

Inside ilastik in tifffile.py in line I see:

![image](https://cloud.githubusercontent.com/assets/3833249/26300912/cb8d8358-3edf-11e7-988a-57c566573f84.png)

**Comment by k-dominik** [comment]
> Maybe stupid remark, but may this be a typo? decodelzw vs decode_lzw

@sebi06 interestingly, in the linux version of the tifffile package it says ```def decodelzw(encoded):```

**Comment by k-dominik** [comment]
@akreshuk I have added the requested test in PR https://github.com/ilastik/lazyflow/pull/240

This test, however, will not indicate the discussed issue. A lot more tests should already fail when [this](https://github.com/ilastik/lazyflow/blob/master/lazyflow/operators/ioOperators/opTiffReader.py#L10) line fails. (and this is the problem in this issue). I wonder if the current tests pass for the windows folks with the release configuration

**Comment by akreshuk** [comment]
hmm, @ukoethe ran all the tests before building the windows binary. I guess it's not that line then or there is a different branch that windows goes into. I'll merge your PR and we'll try to run it on windows

**Comment by FynnBe** [comment]
We tried running the release version on windows10 with this new test file and we have no problem loading it or starting ilastik.

**Comment by akreshuk** [comment]
@sebi06 are you sure you don't have some other version of tifffile.py around, besides the one in the ilastik binary? Could it actually be some older version of ilastik getting in the way here? The current code works fine for us on all platforms.

**Comment by k-dominik** [comment]
ok - then, since we cannot reproduce it, should we just close this issue?

**Comment by akreshuk** [comment]
hold on, the issue is obviously real, perhaps we'll find a way to reproduce.

**Comment by k-dominik** [comment]
@akreshuk this seems dormant, let's close it, i don't think we ever managed to reproduce it
