### ISSUE TITLE
Counting crashes on data input

### ISSUE THREAD

**Issue by akreshuk** [ilastik/ilastik#1250]
Still works in the 1.1.9, but crashes now:

```pytb
RuntimeError: Could not create instance of '<class 'ilastik.applets.counting.opCounting.OpPredictionPipeline'>'
args   = ()
kwargs = {'parent': <ilastik.utility.opMultiLaneWrapper.OpMultiLaneWrapper object at 0x7f208c519590>}
The exception was:
Could not create instance of '<class 'lazyflow.operators.valueProviders.OpPrecomputedInput'>'
args   = ()
kwargs = {'ignore_dirty_input': False, 'parent': <ilastik.applets.counting.opCounting.OpPredictionPipeline object at 0x7f206e18a690>}
The exception was:
__init__() got an unexpected keyword argument 'ignore_dirty_input'
Traceback:
Traceback (most recent call last):
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/operator.py", line 107, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 371, in __init__
    super(OpPrecomputedInput, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ignore_dirty_input'

Traceback:
Traceback (most recent call last):
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/operator.py", line 107, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/ilastik/ilastik/applets/counting/opCounting.py", line 587, in __init__
    self.precomputed_predictions_gui = OpPrecomputedInput( ignore_dirty_input=False, parent=self )
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/operator.py", line 124, in __call__
    raise RuntimeError(err)
RuntimeError: Could not create instance of '<class 'lazyflow.operators.valueProviders.OpPrecomputedInput'>'
args   = ()
kwargs = {'ignore_dirty_input': False, 'parent': <ilastik.applets.counting.opCounting.OpPredictionPipeline object at 0x7f206e18a690>}
The exception was:
__init__() got an unexpected keyword argument 'ignore_dirty_input'
Traceback:
Traceback (most recent call last):
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/operator.py", line 107, in __call__
    instance = ABCMeta.__call__(cls, *args, **kwargs)
  File "/home/akreshuk/miniconda2/envs/ilastik-devel/ilastik-meta/lazyflow/lazyflow/operators/valueProviders.py", line 371, in __init__
    super(OpPrecomputedInput, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ignore_dirty_input'
```

**Comment by stuarteberg** [comment]
I'm pretty sure your version of lazyflow was not in sync with the latest master.

**Comment by stuarteberg** [comment]
... but meanwhile I seem to have broken something else via ilastik/lazyflow@d741924c6562f362c5786572ac454b8d198eed89

**Comment by stuarteberg** [comment]
Now, with the latest commit of lazyflow, the counting workflow works for me.

**Comment by akreshuk** [comment]
works for me too.
