### ISSUE TITLE
Manual Tracking: Plugin Export not implemented

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ilastik#1958]
## Related
https://github.com/ilastik/ilastik/issues/1827 <-- should be closed once this is fixed
https://github.com/ilastik/ilastik/pull/1836
https://github.com/ilastik/ilastik/pull/1831

https://forum.image.sc/t/ilastik-on-linux-problem-exporting-csv-of-manual-tracking/23012/6

## Describe the bug
Plugin-based export is available in Manual Tracking (just by using the correct applet). However, these changes have not been propagated to `manualTrackingWorkflow.py`. Export doesn't work.

## Expected behavior
Export should work

## To Reproduce
Within the Manual tracking workflow
1. Do some tracking
2. Go to `Export`, choose plugin, e.g. csv, export. boom.

## Error message/traceback

If applicable, please add tracebacks with formatting, such as

```pytb
ERROR 2019-02-15 08:50:35,918 log_exception 27204 139705990743808 Traceback (most recent call last):
  File ".../ilastik-meta/ilastik/ilastik/applets/dataExport/dataExportGui.py", line 401, in exportSlots
    exportSuccessful = self.parentApplet.post_process_lane_export(lane_index, checkOverwriteFiles=True)
TypeError: post_process_lane_export() got an unexpected keyword argument 'checkOverwriteFiles'
```

**Comment by alifarhat30** [comment]
This error happens in both Linux and Windows.

**Comment by shak360** [comment]
This seems to be happening on the `1.3.0` build as well, on both Linux and Windows.

**Comment by marnoldini** [comment]
Hi there, it looks like this is still not working in the 1.4.0 beta version. Is it still planned to fix this?
